# _*_ coding: UTF-8 _*_
# Version information START --------------------------------------------------
VERSION_INFO = \
    """
    Author: ZHANG YUBO

    Version-01:
        2020-09  High-Throughput Searches Using Wise2
    """
# Version information END ----------------------------------------------------


import argparse
import os
import sys
import subprocess
os.system('export PATH=$PATH:/data/zhangyubo/wise2.4.1/src/bin/')
os.system('export WISECONFIGDIR=/data/zhangyubo/wise2.4.1/wisecfg/')
PATHGENBLASTA = '/data/zhangyubo/wise2.4.1/genblasta_v1.0.4_linux_x86_64'
PATHGENEWISE = '/data/zhangyubo/wise2.4.1/src/bin/genewise'
STRANDDICT = {'+':'-tfor', '-':'-trev'}

###############################################################################
# function part
###############################################################################
class FastaIndex(object):
    # index reference fasta
    def __init__(self, index_line_list):
        self.NAME = index_line_list[0]
        self.LENGTH = int(index_line_list[1])
        self.OFFSET = int(index_line_list[2])
        self.LINEBASES = int(index_line_list[3])
        self.LINEWIDTH = int(index_line_list[4])


###############################################################################
# read parameters
###############################################################################
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="format conversion")
    parser.add_argument("-q", "--Query",
                        help="Input protein file. Index file generated by samtools in the same directory is also required", required=True)
    parser.add_argument("-r", "--Reference", required=True,
                        help="Input reference fasta file. Index file generated by samtools in the same directory is also required")
    parser.add_argument("-o", "--Output",
                        help="Output file name", required=False)    


    # -------------------------------------------------------------------->>>>>
    # load the parameters
    # -------------------------------------------------------------------->>>>>
    ARGS = parser.parse_args()
   

    # -------------------------------------------------------------------->>>>>
    # Build index for reference and query fasta
    # -------------------------------------------------------------------->>>>>
    if os.path.exists("%s.fai" % ARGS.Reference):
        ReferenceIndexList = []
        with open("%s.fai" % ARGS.Reference, 'r') as ReferenceIndex:
            lines = ReferenceIndex.readlines()
            for line in lines:
                line = line.split()
                ReferenceIndexList.append(FastaIndex(line))
    else:
        print("There is no index file for reference fasta. Program exit.")
        sys.exit()


    if os.path.exists("%s.fai" % ARGS.Query):
        QueryIndexList = []
        with open("%s.fai" % ARGS.Query, 'r') as QueryIndex:
            lines = QueryIndex.readlines()
            for line in lines:
                line = line.split()
                QueryIndexList.append(FastaIndex(line))
    else:
        print("There is no index file for query fasta. Program exit.")
        sys.exit()


    # -------------------------------------------------------------------->>>>>
    # Read reference fasta
    # -------------------------------------------------------------------->>>>>
    ReferenceFasta = open(ARGS.Reference, 'r')
    ReferenceFastaDict = {}
    for Chr in ReferenceIndexList:
        ReferenceFasta.seek(Chr.OFFSET, 0)
        RefSeq = ReferenceFasta.read(Chr.LENGTH // Chr.LINEBASES * Chr.LINEWIDTH + Chr.LENGTH % Chr.LINEBASES)
        RefSeq = RefSeq.replace('\n', '')
        ReferenceFastaDict[Chr.NAME] = RefSeq


    QueryFasta = open(ARGS.Query, 'r')
    for Query in QueryIndexList:
        FLAG = True
        with open (Query.NAME + '.fa', 'w') as tempout:
            tempout.write('>' + Query.NAME + '\n')
            QueryFasta.seek(Query.OFFSET, 0)
            QuerySeq = QueryFasta.read(Query.LENGTH // Query.LINEBASES * Query.LINEWIDTH + Query.LENGTH % Query.LINEBASES)
            QuerySeq = QuerySeq.replace('\n', '')
            tempout.write(QuerySeq + '\n')

        
        subprocess.run("%s -q %s.fa -t %s -e 1e-5" %(PATHGENBLASTA, Query.NAME, ARGS.Reference), shell=True)    
        with open (Query.NAME + '.fa.gblast', 'r') as tempin:
            lines = tempin.readlines()
            for line in lines:
                if '|' in line:

                    tempref = line.split('|')[1]
                    tempchr = tempref.split(':')[0]
                    tempstart = tempref.split(':')[1].split('..')[0]
                    tempend = tempref.split(':')[1].split('..')[1]
                    tempstrand = STRANDDICT[line.split('|')[2]]

                    with open ('Ref.fa', 'w') as tempout:
                        tempout.write('>' + tempchr + '_' + tempstart + '\n')
                        tempseq = ReferenceFastaDict[tempchr][int(tempstart)-1:int(tempend)]
                        tempout.write(tempseq + '\n')
                    subprocess.run('echo "###%s" >> %s' % (Query.NAME, ARGS.Output), shell=True)   
                    subprocess.run("%s %s.fa Ref.fa %s -genes -gff -alg 2193 >> %s" %(PATHGENEWISE, Query.NAME, tempstrand, ARGS.Output), shell=True)
        subprocess.run("rm -rf %s.fa %s.fa.blast %s.fa.gba.report %s.fa.gblast" %(Query.NAME, Query.NAME, Query.NAME, Query.NAME), shell=True)
